export const businessTypeOptions = [
  { value: 'restaurant', label: 'Restaurant & Food' },
  { value: 'retail', label: 'Retail & Shopping' },
  { value: 'healthcare', label: 'Healthcare & Medical' },
  { value: 'fitness', label: 'Fitness & Wellness' },
  { value: 'technology', label: 'Technology & Software' },
  { value: 'consulting', label: 'Consulting & Services' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'education', label: 'Education & Training' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'hospitality', label: 'Hospitality & Travel' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'financial', label: 'Financial Services' },
  { value: 'nonprofit', label: 'Non-Profit' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'construction', label: 'Construction' },
  { value: 'creative', label: 'Creative & Design' },
  { value: 'sports', label: 'Sports & Recreation' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'energy', label: 'Energy & Utilities' },
  { value: 'telecom', label: 'Telecommunications' },
  { value: 'media', label: 'Media & Publishing' },
  { value: 'legal', label: 'Legal Services' },
  { value: 'insurance', label: 'Insurance' },
  { value: 'pharmaceutical', label: 'Pharmaceutical' },
  { value: 'biotechnology', label: 'Biotechnology' },
  { value: 'aerospace', label: 'Aerospace & Defense' },
  { value: 'marine', label: 'Marine & Maritime' },
  { value: 'mining', label: 'Mining & Resources' },
  { value: 'chemical', label: 'Chemical' },
  { value: 'textile', label: 'Textile & Apparel' },
  { value: 'furniture', label: 'Furniture & Home' },
  { value: 'jewelry', label: 'Jewelry & Accessories' },
  { value: 'art', label: 'Art & Antiques' }
];
